# 作業目標:
    了解 Convolution 卷積的組成

# 作業重點:
    修改 a_slice_prev, 檢查 Z 的輸出

In [7]:
import numpy as np

In [8]:
# GRADED FUNCTION: conv_single_step
def conv_single_step(a_slice_prev, W, b):
    """
    定義一層 Kernel (內核), 使用的參數說明如下
    Arguments:
        a_slice_prev -- 輸入資料的維度
        W -- 權重, 被使用在 a_slice_prev
        b -- 偏差參數 
    Returns:
        Z -- 滑動窗口（W，b）卷積在前一個 feature map 上的結果
    """

    # 定義一個元素介於 a_slice and W
    s = a_slice_prev * W
    # 加總所有的 "s" 並指定給Z.
    Z = np.sum(s)
    # Add bias b to Z. 這是 float() 函數,
    Z = float(Z + b)

    return Z

In [9]:
np.random.seed(5)
#定義一個 axaxd 的 feature map
a_slice_prev = np.random.randn(5,5,3) 
W = np.random.randn(5,5,3)
b = np.random.randn(1, 1, 1)

#取得計算後,卷積矩陣的值
Z = conv_single_step(a_slice_prev, W, b)
print("a_slice_prev = ", a_slice_prev)
print("W= ", W)
print("b= ", b)
print("Z =", Z)

a_slice_prev =  [[[ 0.44122749 -0.33087015  2.43077119]
  [-0.25209213  0.10960984  1.58248112]
  [-0.9092324  -0.59163666  0.18760323]
  [-0.32986996 -1.19276461 -0.20487651]
  [-0.35882895  0.6034716  -1.66478853]]

 [[-0.70017904  1.15139101  1.85733101]
  [-1.51117956  0.64484751 -0.98060789]
  [-0.85685315 -0.87187918 -0.42250793]
  [ 0.99643983  0.71242127  0.05914424]
  [-0.36331088  0.00328884 -0.10593044]]

 [[ 0.79305332 -0.63157163 -0.00619491]
  [-0.10106761 -0.05230815  0.24921766]
  [ 0.19766009  1.33484857 -0.08687561]
  [ 1.56153229 -0.30585302 -0.47773142]
  [ 0.10073819  0.35543847  0.26961241]]

 [[ 1.29196338  1.13934298  0.4944404 ]
  [-0.33633626 -0.10061435  1.41339802]
  [ 0.22125412 -1.31077313 -0.68956523]
  [-0.57751323  1.15220477 -0.10716398]
  [ 2.26010677  0.65661947  0.12480683]]

 [[-0.43570392  0.97217931 -0.24071114]
  [-0.82412345  0.56813272  0.01275832]
  [ 1.18906073 -0.07359332 -2.85968797]
  [ 0.7893664  -1.87774088  1.53875615]
  [ 1.82136474 -